M48
; DRILL file {KiCad 8.0.4} date 2024-09-03T12:05:10-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-03T12:05:10-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X6.8919Y-2.4902
X6.8919Y-3.587
X6.9Y-4.2386
T2
X5.1545Y-2.6244
X5.3455Y-2.6244
T3
X5.1427Y-2.5051
X5.3573Y-2.5051
M30
